options:
    docker: true
image: transentis/buildenv #python image with awscli and awsebcli installed

pipelines:
    branches:
        release/test:
            - step:
                deployment: test
                name: 'Deploy to development environment'
                script:
                      - cd rest-api
                      - AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY} eb use sim-covid-api-dev
                      - AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY} eb deploy
        release/prod:
            - step:
                deployment: prod
                name: 'Deploy to production environment'
                script:
                      - cd rest-api
                      - AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY} eb use sim-covid-api-prod
                      - AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY} eb deploy