options:
    docker: true
image: transentis/buildenv #python image with awscli and awsebcli installed

pipelines:
    branches:
        release/test:
            - step:
                name: 'Build zip file'
                script:
                      - cd rest-api
                      - zip -r application.zip .
                artifacts:
                      - application.zip
            - step:
                name: 'Deploy to development environment'
                deployment: Test
                script:
                  - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
                    variables:
                        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                        AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
                        APPLICATION_NAME: '$AWS_APPLICATION_NAME'
                        ENVIRONMENT_NAME: '$AWS_ENVIRONMENT_NAME'
                        S3_BUCKET: '$AWS_S3_BUCKET'
                        ZIP_FILE: 'application.zip'
                        WAIT: 'true'
        release/prod:
            - step:
                name: 'Build zip file'
                script:
                      - cd rest-api
                      - zip -r application.zip .
                artifacts:
                      - application.zip
            - step:
                name: 'Deploy to production environment'
                deployment: Production
                script:
                  - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
                    variables:
                        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                        AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
                        APPLICATION_NAME: '$AWS_APPLICATION_NAME'
                        ENVIRONMENT_NAME: '$AWS_ENVIRONMENT_NAME'
                        S3_BUCKET: '$AWS_S3_BUCKET'
                        ZIP_FILE: 'application.zip'
                        WAIT: 'true'

