branch-defaults:
  default:
    environment: sim-covid-api-dev
    group_suffix: null
global:
  application_name: sim-covid-api
  branch: null
  default_ec2_keyname: rest-api-server 
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null 
  repository: null
  sc: null
  workspace_type: Application
